service: service-name

plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-offline

custom: ${file(../../config/custom.${opt:stage, "local"}.js)}

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(../../config/provider.environment.${opt:stage, "local"}.js)}

functions:
  hello:
    handler: handlers.hello
    timeout: 300
