service: gql

plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-offline

custom: ${file(../../config/custom.${opt:stage, "local"}.js)}

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(../../config/provider.environment.${opt:stage, "local"}.js)}

functions:
  Authorizer:
    handler: handlers.authorizer
    timeout: 300
  Login:
    handler: handlers.login
    timeout: 300
    events:
      - http:
          path: login
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
  GraphQL:
    handler: handlers.graphql
    timeout: 300
    events:
      - http:
          path: graphql
          method: get
          authorizer: Authorizer
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: true
  GraphiQL:
    handler: handlers.graphiql
    timeout: 300
    events:
      - http:
          path: graphiql
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: true
  Playground:
    handler: handlers.playground
    timeout: 300
    events:
      - http:
          path: playground
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: true
